# Generated by Django 4.1.4 on 2023-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_of_owner',
            field=models.CharField(default='Anonim', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None, max_length=14, null=True),
        ),
    ]
