# Generated by Django 4.1.4 on 2022-12-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0002_alter_item_description_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cloth.productimage'),
        ),
    ]
