# Generated by Django 4.1.4 on 2023-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0002_item_email_item_name_of_owner_item_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Shop/Cloth/static/item_photos'),
        ),
    ]
