# Generated by Django 4.1.4 on 2023-01-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0003_alter_item_phone_number_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.productimage'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Shop/Cloth/static/item_photos'),
        ),
    ]
