# Generated by Django 4.1.4 on 2023-01-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0004_alter_item_item_img_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_of_owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.productimage'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/item_photos'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cloth.item'),
        ),
    ]
